name: release
on:
  push:
    branches:
      - main

jobs:
  release:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.semanticRelease.outputs.semanticVersion }}
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install dependencies
        run: npm install -D @semantic-release/exec conventional-changelog-conventionalcommits
      - name: Generate release notes and tag
        id: semanticRelease
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        run: npx semantic-release

  build:
    runs-on: ubuntu-latest
    needs: release
    if: needs.release.outputs.version
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Set up Docker Buildx
        uses: docker/setup-buildx-action@v2
      - name: Login
        uses: docker/login-action@v2
        with:
          username: ${{ secrets.DOCKER_USER }}
          password: ${{ secrets.DOCKER_PASS }}
      - name: Build and push container
        uses: docker/build-push-action@v4
        with:
          tags: |
            ${{ vars.DOCKER_REPOSITORY }}:${{ needs.release.outputs.version }}
            ${{ vars.DOCKER_REPOSITORY }}:latest
          push: true
